// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Box: typeof import('vue-termui')['TuiBox']
    DominoTile: typeof import('./src/components/DominoTile.vue')['default']
    HandDominoTile: typeof import('./src/components/HandDominoTile.vue')['default']
    Text: typeof import('vue-termui')['TuiText']
  }
}

export {}
