// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Newline: typeof import('vue-termui')['TuiNewline']
    Progressbar: typeof import('vue-termui')['TuiProgressBar']
    Text: typeof import('vue-termui')['TuiText']
  }
}
