import type { StyleDefinitionInput } from 'vue-termui'

/**
 * Example markdown syntax themes for the playground.
 *
 * These are *not* part of the vue-termui API — a theme is just a map of token
 * scopes to styles that you hand to `SyntaxStyle.fromStyles(...)` and pass to
 * `<Markdown :syntax-style="...">`. Copy any of these into your own app and
 * tweak the colors. The scope names (`markup.*` for markdown structure,
 * `keyword`/`string`/… for fenced-code syntax) are shared across all themes.
 */
export interface MarkdownTheme {
  name: string
  /** Base foreground, passed as `<Markdown :fg>`. */
  fg: string
  /** Base background, passed as `<Markdown :bg>` (panels/code blocks). */
  bg: string
  /** Token scope → style map for `SyntaxStyle.fromStyles(...)`. */
  styles: Record<string, StyleDefinitionInput>
}

export const markdownThemes: MarkdownTheme[] = [
  {
    name: 'GitHub Dark',
    fg: '#e6edf3',
    bg: '#0d1117',
    styles: {
      default: { fg: '#e6edf3' },
      'markup.heading': { fg: '#58a6ff', bold: true },
      'markup.heading.1': { fg: '#00ff88', bold: true, italic: true, underline: true },
      'markup.heading.2': { fg: '#00d7ff', bold: true },
      'markup.heading.3': { fg: '#ff69b4' },
      'markup.bold': { fg: '#f0f6fc', bold: true },
      'markup.strong': { fg: '#f0f6fc', bold: true },
      'markup.italic': { fg: '#f0f6fc', italic: true },
      'markup.list': { fg: '#ff7b72' },
      'markup.quote': { fg: '#8b949e', italic: true },
      'markup.raw': { fg: '#a5d6ff', bg: '#161b22' },
      'markup.raw.block': { fg: '#a5d6ff', bg: '#161b22' },
      'markup.raw.inline': { fg: '#a5d6ff', bg: '#161b22' },
      'markup.link': { fg: '#58a6ff', underline: true },
      'markup.link.label': { fg: '#a5d6ff', underline: true },
      'markup.link.url': { fg: '#58a6ff', underline: true },
      keyword: { fg: '#ff7b72', bold: true },
      string: { fg: '#a5d6ff' },
      comment: { fg: '#8b949e', italic: true },
      number: { fg: '#79c0ff' },
      function: { fg: '#d2a8ff' },
      type: { fg: '#ffa657' },
      operator: { fg: '#ff7b72' },
      variable: { fg: '#e6edf3' },
      property: { fg: '#79c0ff' },
      label: { fg: '#7ee787' },
      'punctuation.bracket': { fg: '#f0f6fc' },
      'punctuation.delimiter': { fg: '#c9d1d9' },
      'punctuation.special': { fg: '#8b949e' },
      'diff.plus': { fg: '#3fb950' },
      'diff.minus': { fg: '#f85149' },
      conceal: { fg: '#6e7681' },
    },
  },
  {
    name: 'GitHub Light',
    fg: '#24292f',
    bg: '#ffffff',
    styles: {
      default: { fg: '#24292f' },
      'markup.heading': { fg: '#0550ae', bold: true },
      'markup.heading.1': { fg: '#1a7f37', bold: true, italic: true, underline: true },
      'markup.heading.2': { fg: '#0550ae', bold: true },
      'markup.heading.3': { fg: '#8250df' },
      'markup.bold': { fg: '#24292f', bold: true },
      'markup.strong': { fg: '#24292f', bold: true },
      'markup.italic': { fg: '#24292f', italic: true },
      'markup.list': { fg: '#cf222e' },
      'markup.quote': { fg: '#6e7781', italic: true },
      'markup.raw': { fg: '#24292f', bg: '#f6f8fa' },
      'markup.raw.block': { fg: '#24292f', bg: '#f6f8fa' },
      'markup.raw.inline': { fg: '#24292f', bg: '#f6f8fa' },
      'markup.link': { fg: '#0969da', underline: true },
      'markup.link.label': { fg: '#0a3069', underline: true },
      'markup.link.url': { fg: '#0969da', underline: true },
      keyword: { fg: '#cf222e', bold: true },
      string: { fg: '#0a3069' },
      comment: { fg: '#6e7781', italic: true },
      number: { fg: '#0550ae' },
      function: { fg: '#8250df' },
      type: { fg: '#953800' },
      operator: { fg: '#cf222e' },
      variable: { fg: '#24292f' },
      property: { fg: '#0550ae' },
      label: { fg: '#1a7f37' },
      'punctuation.bracket': { fg: '#24292f' },
      'punctuation.delimiter': { fg: '#57606a' },
      'punctuation.special': { fg: '#57606a' },
      'diff.plus': { fg: '#1a7f37' },
      'diff.minus': { fg: '#cf222e' },
      conceal: { fg: '#6e7781' },
    },
  },
  {
    name: 'Monokai',
    fg: '#f8f8f2',
    bg: '#272822',
    styles: {
      default: { fg: '#f8f8f2' },
      'markup.heading': { fg: '#a6e22e', bold: true },
      'markup.heading.1': { fg: '#f92672', bold: true, italic: true, underline: true },
      'markup.heading.2': { fg: '#66d9ef', bold: true },
      'markup.heading.3': { fg: '#e6db74' },
      'markup.bold': { fg: '#f8f8f2', bold: true },
      'markup.strong': { fg: '#f8f8f2', bold: true },
      'markup.italic': { fg: '#f8f8f2', italic: true },
      'markup.list': { fg: '#f92672' },
      'markup.quote': { fg: '#75715e', italic: true },
      'markup.raw': { fg: '#e6db74', bg: '#3e3d32' },
      'markup.raw.block': { fg: '#e6db74', bg: '#3e3d32' },
      'markup.raw.inline': { fg: '#e6db74', bg: '#3e3d32' },
      'markup.link': { fg: '#66d9ef', underline: true },
      'markup.link.label': { fg: '#e6db74', underline: true },
      'markup.link.url': { fg: '#66d9ef', underline: true },
      keyword: { fg: '#f92672', bold: true },
      string: { fg: '#e6db74' },
      comment: { fg: '#75715e', italic: true },
      number: { fg: '#ae81ff' },
      function: { fg: '#a6e22e' },
      type: { fg: '#66d9ef', italic: true },
      operator: { fg: '#f92672' },
      variable: { fg: '#f8f8f2' },
      property: { fg: '#a6e22e' },
      label: { fg: '#a6e22e' },
      'punctuation.bracket': { fg: '#f8f8f2' },
      'punctuation.delimiter': { fg: '#f8f8f2' },
      'punctuation.special': { fg: '#75715e' },
      'diff.plus': { fg: '#a6e22e' },
      'diff.minus': { fg: '#f92672' },
      conceal: { fg: '#75715e' },
    },
  },
  {
    name: 'Nord',
    fg: '#d8dee9',
    bg: '#2e3440',
    styles: {
      default: { fg: '#d8dee9' },
      'markup.heading': { fg: '#88c0d0', bold: true },
      'markup.heading.1': { fg: '#8fbcbb', bold: true, italic: true, underline: true },
      'markup.heading.2': { fg: '#81a1c1', bold: true },
      'markup.heading.3': { fg: '#b48ead' },
      'markup.bold': { fg: '#eceff4', bold: true },
      'markup.strong': { fg: '#eceff4', bold: true },
      'markup.italic': { fg: '#eceff4', italic: true },
      'markup.list': { fg: '#81a1c1' },
      'markup.quote': { fg: '#616e88', italic: true },
      'markup.raw': { fg: '#a3be8c', bg: '#3b4252' },
      'markup.raw.block': { fg: '#a3be8c', bg: '#3b4252' },
      'markup.raw.inline': { fg: '#a3be8c', bg: '#3b4252' },
      'markup.link': { fg: '#88c0d0', underline: true },
      'markup.link.label': { fg: '#a3be8c', underline: true },
      'markup.link.url': { fg: '#88c0d0', underline: true },
      keyword: { fg: '#81a1c1', bold: true },
      string: { fg: '#a3be8c' },
      comment: { fg: '#616e88', italic: true },
      number: { fg: '#b48ead' },
      function: { fg: '#88c0d0' },
      type: { fg: '#8fbcbb' },
      operator: { fg: '#81a1c1' },
      variable: { fg: '#d8dee9' },
      property: { fg: '#88c0d0' },
      label: { fg: '#a3be8c' },
      'punctuation.bracket': { fg: '#eceff4' },
      'punctuation.delimiter': { fg: '#d8dee9' },
      'punctuation.special': { fg: '#616e88' },
      'diff.plus': { fg: '#a3be8c' },
      'diff.minus': { fg: '#bf616a' },
      conceal: { fg: '#4c566a' },
    },
  },
]
